// 方便书写和检测
export const SET_OPEN_ID = 'SET_OPEN_ID';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_FREE_TO_CART = 'ADD_FREE_TO_CART';
export const DECREMENT_INVENTORY = 'DECREMENT_INVENTORY';
export const INCREMENT_INVENTORY = 'INCREMENT_INVENTORY';
export const DEL_PRODUCT_FROM_CART = 'DEL_PRODUCT_FROM_CART';
export const DEL_FREE_FROM_CART = 'DEL_FREE_FROM_CART';

export const UPDATE_FREE_FROM_CART = 'UPDATE_FREE_FROM_CART';
export const CHECK_OUT_CART = 'CHECK_OUT_CART';
export const CHECK_OUT_FREE_CART = 'CHECK_OUT_FREE_CART';
export const TOKEN = 'TOKEN';
export const LOG_OUT = 'LOG_OUT';
export const IS_LOGIN = 'IS_LOGIN';
export const IS_VIP = 'IS_VIP';

export const ADD_CURRENT_LOCATION = 'ADD_CURRENT_LOCATION';
